### ISSUE TITLE
Write more detailed contributing guidelines

### ISSUE THREAD

**Issue by samanpwbb** [mapbox/maki-2#23]
- Guidelines on how to choose which points of interest to make icons for, with examples.
- Guidelines on how to choose the right symbol, with examples.
- Detailed visual guidelines for how to draw icons: what border radius should I use for rounded corners? What line-weight should icons with strokes have? What should the relationship be between the 11px icon  and the 15px icon?
- Explain how the automated tests work.

**Comment by natslaughter** [comment]
I am attaching the first iteration of Maki 2 contributing guidelines doc.  
Notes on next steps are in pink on pages.  In general, it needs more detailed visual guidelines and testing to make sure A: it works, and B: other rules or items that should be mentioned aren't being left out.  
I will email @samanpwbb and @nickidlugash the working files tomorrow morning. 

[*Maki2_Guidelines.pdf](https://github.com/mapbox/maki-2/files/100127/Maki2_Guidelines.pdf)

**Comment by samanpwbb** [comment]
Nat is doing this, follow up work in https://github.com/mapbox/maki-icons/
