### ISSUE TITLE
reorganize subfolders

### ISSUE THREAD

**Issue by nickidlugash** [mapbox/maki-2#24]
Specifically:

- Split the `general` folder into 3 folders, incl. and `extras` folder for any icon that doesn't directly correspond to Streets data
- Add in all applicable icons from other subfolder to the `extras` folder

**Comment by samanpwbb** [comment]
I would prefer to organize the icons with a separate json doc and then move all the icons to one folder. This would make it possible to apply more than one structure. (iD could have one, Mapbox Streets could have one, ect).

**Comment by nickidlugash** [comment]
@samanpwbb sounds good :+1: I can help write the doc for Mapbox Streets.

**Comment by natslaughter** [comment]
Reorganized .svg files into one folder: maki-2/icons

**Comment by natslaughter** [comment]
Reopened issue. A json doc needs to be created that organizes icon files.

**Comment by samanpwbb** [comment]
Done in the `maki-2.0` branch of maki: https://github.com/mapbox/maki/tree/maki-2.0/layouts
