### ISSUE TITLE
building custom collections

### ISSUE THREAD

**Issue by nebulon42** [mapbox/maki-2#34]
For Osmic I have written a script that is capable of building custom icon collections and exporting this collection in different formats like SVG (with recolouring or shields), PNG or icon fonts. It is now quite flexible, but maybe still a bit homegrown in terms of its architecture.

Details at https://github.com/gmgeo/osmic/blob/master/tools/export.md and https://github.com/gmgeo/osmic/blob/master/tools/export.py

Would something like that be an option for Maki 2? I'm also open for the idea of creating a cross-repository icon collection build tool. Doesn't necessarily have to be in Python.

**Comment by samanpwbb** [comment]
See https://github.com/mapbox/maki-chef/issues/11 – the maki chef project might interest you @nebulon42

**Comment by nebulon42** [comment]
This is great. Not exactly what I had in mind, but if maki-chef would be scriptable it would be a really versatile tool.
