### ISSUE TITLE
add `entrance` icon

### ISSUE THREAD

**Issue by nickidlugash** [mapbox/maki-2#44]
We use an `entrance` icon in the `rail_station_label` layer of Mapbox Streets data, and for some reason it's missing from this repo. The icon [lives in the Streets style](https://github.com/mapbox/mapbox-gl-styles/blob/master/sprites/streets-v8/_svg/entrance.svg) (although this version is the `entrance` icon + background square).  

Old Maki had a [different icon entirely for `entrance`](https://github.com/mapbox/maki/blob/mb-pages/src/entrance-12.svg).

I don't like either design – both are hard to understand in their context, and the current stairs design is a bit too bullky, considering that you usually see multiple instances of this icon clustered together.

@natslaughter want to take a stab at designing a new icon? @samanpwbb suggested maybe an escalator:

![](https://cdn4.iconfinder.com/data/icons/dot/256/escalator_2.png)

![](http://thumb7.shutterstock.com/display_pic_with_logo/708472/370886735/stock-vector-blue-colored-icon-of-escalator-on-gray-color-background-eps-370886735.jpg)

(Probably without any arrows)

This would be a great icon to use to walk through the workflow of testing new icons directly on maps  (since the context of this icon is so important to the design). Grab me whenever you want and we can go through this!

**Comment by amyleew** [comment]
:+1: Just ran into this missing `entrance` icon as a [failing test](https://gist.github.com/amyleew/935bbb70136245045474) in [`bright-v8`](https://github.com/mapbox/mapbox-gl-styles/tree/master/sprites/bright-v8/_svg). When this icon is ready, I'll add it to `bright-v8`, the test will be passing, and I'll be able to merge https://github.com/mapbox/mapbox-gl-styles/pull/277.

**Comment by natslaughter** [comment]
@nickidlugash, sure thing. I will push this to the top of the Maki 2 list. 

I think the escalator works as an entrance icon when the grade changes - going to a subterranean subway line or an elevated track. Do you also need an entrance icon for uses where the grade stays the same - ground plane platforms?

**Comment by natslaughter** [comment]
Hello @nickidlugash, @amyleew,
I'm sharing some screenshots of two types of usage for the new entrance icon. One shows just the icon with no shield, and the other has a shield. Let me know what you think.

<img width="685" alt="bare icon" src="https://cloud.githubusercontent.com/assets/16616543/13614640/845753a6-e53f-11e5-9761-316ebbceb0bc.png">
<img width="686" alt="icon with shield" src="https://cloud.githubusercontent.com/assets/16616543/13614641/845bff28-e53f-11e5-95c4-7d7838f50cf8.png">

**Comment by amyleew** [comment]
Thanks for hitting this @natslaughter! 

I think all the `entrance` data points do represent only [`subway-entrances`](https://github.com/mapbox/mapbox-streets-source.tm2source/blob/ec529b3c5463057502fcdece80be4a7325295dfa/pgsql/carto_table_updates.sql#L816-L817). The version with no shield is a better read and less bulky, which would help with the clustering that typically happens since these POIs are often nearby each other.

I can pull the current version of your icon to get a passing test, then update it with your final version as you continue to finesse it.

**Comment by samanpwbb** [comment]
Closed by https://github.com/mapbox/maki-2/pull/45
