### ISSUE TITLE
maki icons to fix based on design guidelines

### ISSUE THREAD

**Issue by natslaughter** [mapbox/maki-2#59]
Some of the older maki icons still have some issues with pixel alignment and spacing. In order to get the entire set to adhere to the new design guidelines, we need to go back and edit some icons

I started to make a list here of icons that need final tweaks, however it seems like most of them need very minor tweaks. Rather than just make a list, it might be more efficient to sit down with @nickidlugash and @samanpwbb, go over the guidelines, and have Nicki and I parse up the work.

Let me know when we could meet up!

**Comment by samanpwbb** [comment]
See https://github.com/mapbox/maki/issues/240
